services:
  # Бэкенд (Django)
  - type: web
    name: rksp-backend
    env: docker
    build:
      context: ./rksp_backend
      dockerfile: Dockerfile
    envVars:
      - key: DEBUG
        value: "1"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"  # или *.onrender.com
    port: 8000

  # Фронтенд (React)
  - type: web
    name: rksp-frontend
    env: docker
    build:
      context: ./rksp_frontend
      dockerfile: Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://rksp-backend.onrender.com  # URL бэкенда на Render
    port: 3000