# Generated by Django 4.2.20 on 2025-05-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_customuser_abonement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='abonement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonement', to='schedule.abonementtype'),
        ),
        migrations.AlterField(
            model_name='abonement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonement', to=settings.AUTH_USER_MODEL),
        ),
    ]
