# Generated by Django 4.2.20 on 2025-05-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_abonement_abonement_type_alter_abonement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements', to=settings.AUTH_USER_MODEL),
        ),
    ]
